name: google_maps_custom_tooltip
description: Custom tooltip widget that appears above a marker in a Google Map.
version: 0.0.3
homepage: https://github.com/hchaviano/google_maps_custom_tooltip
platforms:
  android:
  ios:
  web:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.4+2
  pointer_interceptor: ^0.9.3+6

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
